services:
    webgps:
        build: .
        container_name: gnss-frontend
        restart: always
        volumes:
            - .env:/app/.env
            - ./srv/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "${APP_PORT}:5100"
        depends_on:
            - backend
